### ISSUE TITLE
RGB theme is no longer RGB

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#147]
The RGB theme doesn't actually make any of the stage content RGB. The selectors are there but there's obviously a problem. 
```css
#index.theme-rgb .nav-link,
#index.theme-rgb .stage .icon,
#index.theme-rgb .doors i,
#index.theme-rgb .links i,
#index.theme-rgb #themePopup,
#index.theme-rgb #themePopup #closeButton {
  animation: rgb 5s linear infinite !important;
}
```
